# Generated by Django 5.2.7 on 2025-10-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.CharField(max_length=255, unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.JSONField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('character_frequency_map', models.JSONField()),
            ],
        ),
    ]
