# Generated by Django 5.2.7 on 2025-10-21 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringanalysis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
